---
title: "Python from RStudio"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r}
library(reticulate)
os <- import("os")
os$listdir(".")

py_config()
use_condaenv(condaenv = "r-reticulate")
# py_install("pandas")
# py_install("scipy")

scipy <- import("scipy")
scipy$amin(c(1,3,5,7))



```

## Text mining example

### Install required Python libraries
```{r}
#py_install("nltk")
#py_install("nltk.corpus")
#py_install("nltk.tokenize")
```

```{python}
# Importing necessary libraries
import pandas as pd
import numpy as np
import nltk
import os
import nltk.corpus# sample text for performing tokenization
nltk.download("punkt")
text = "In Brazil they drive on the right-hand side of the road. Brazil has a large coastline on the eastern side of South America"# importing word_tokenize from nltk
from nltk.tokenize import word_tokenize# Passing the string text into word tokenize for breaking the sentences
token = word_tokenize(text)
token



```

